### ISSUE TITLE
OSM stylesheet

### ISSUE THREAD

**Issue by Pontorez** [sputnik-maps/gopnik#2]
Hello!
Sorry for offtopic. I accidentally found nice-looking map at http://maps.sputnik.ru/ .
What CartoCSS stylesheet do you use to render it? Do you plan to publish the stylesheet at Github?
Many thanks

**Comment by orofarne** [comment]
Hi!
There are a couple of styles on it. All styles is intellectual property of sputnik.ru and will never been published. Feel free to use API.
