### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by carrbrpoa** [sputnik-maps/gopnik#8]
Hello,

How do you configure and operate gopnik for multiple RenderPools? (I guess it's the term)

What I wish to objectively achieve is: have two options of OSM styles - a custom and the original - want both cached and my applications should reach one or another, depending on it's needs.

Thanks in advance

**Comment by bullgare** [comment]
I guess, @orofarne could help you with that question.

**Comment by carrbrpoa** [comment]
Closing for innactivity
